# This file customizes the default Docker Compose setup for your Astro project.
# For more info, see: https://docs.docker.com/compose/extends/
services:
  postgres:
    # Mounts the local SQL script into the Postgres container's initialization directory.
    # This script will be executed only when the database is first initialized.
    # For more info, see: https://hub.docker.com/_/postgres#initialization-scripts
    volumes:
      - ./include/demo_db_create.sql:/docker-entrypoint-initdb.d/demo_db_create.sql

  # Mounts the local dbt directory into the Airflow containers.
  # This allows you to run dbt commands and access dbt models from within Airflow.
  webserver:
    volumes:
      - ./dbt:/usr/local/airflow/dbt
  scheduler:
    volumes:
      - ./dbt:/usr/local/airflow/dbt